#!/bin/bash
path="/home/juitblip/apps/covid.milchbartstrasse.de/"

# Tell Node to use the Production environment
export NODE_ENV=production

echo "========= GIT CHECKOUT ========="
GIT_WORK_TREE=$path git checkout -f main

# Speed up NPM (see https://stackoverflow.com/a/35308864)
npm set progress=false

echo "========= npm install =========="
cd "$path"
npm install --no-audit

echo "===== RESTART APPLICATION ======"
supervisorctl restart covid-milchbartstrasse

echo "============= DONE ============="
